### PR TITLE
Recipe Tweaks

### PR DESCRIPTION
**Pull request by MuteTiefling**
- AE2 can be rough to get into while doing other mods, due to the heavy iron cost. 
This would allow players to use the far more abundant Tin as well for most recipes. 

- Remove mek sulfur from yellow dye tag and converted to a craft conversion instead.
- Large animals such as cows now drop bones on death. 
- All bladed weapons count as butcher's knives for getting occultism tallow
- Rotten Meat can be manufactured from regular meat
- All candles are `#minecraft:candles` now. https://github.com/EnigmaticaModpacks/Enigmatica10/issues/29
-   Blaze Rods may be obtained through material transformations in addition to mob drops
- Genetics Resequenced quests!

Recipe Conflicts
- Functional Storage and Handcrafted have several conflicts. Drawers will now use framed chests for their crafts and Handcrafted will use regular wooden chests.
- Handcrafted sheets conflict with Comforts sleeping bags. Converted from shapeless to shaped to resolve.

### CODE REVIEW

**Comment by NielsPilgaard** [comment]
> Black dye can be crafted from coals now.

I'm not a fan of this one to be honest, I like having to hunt squids :P

**Comment by MuteTiefling** [comment]
Fair enough, I'll back that one out.

**Comment by NielsPilgaard** [comment]
Thank you 😊

The rest is lovely so far!

**Comment by MuteTiefling** [comment]
Think I'm done with this one for now as well.

**Review by NielsPilgaard — APPROVED** [review]
LGTM 👍

**Pull request merged**
