### PR TITLE
swap to server

### PR DESCRIPTION
**Pull request by MuteTiefling**
KubeJS now has native support for EMI. Recipe Viewer scripts are recommended in Server Scripts. 

Re-creating and moving to Server.

Current Issues:
https://discord.com/channels/303440391124942858/1260988828517400750
https://discord.com/channels/303440391124942858/1260990961891151923

### CODE REVIEW

**Comment by MuteTiefling** [comment]
@NielsPilgaard Not really sure what to do about the tooltips script. I kinda don't like that `emi_hidden_disabled` needs to reside in both client and server to make both of these scripts happy. 

Do we simply forgo the tooltip addition for disabled items?
Also, our typical info pane on disabled items won't work since a removal in EMI completely hides all panes. So the info pane simply doesn't show on anything we disable.

**Comment by Kanzaji** [comment]
We could technically rework the `emi_hidden_disabled` scripts from being just a scripts that defines constants, to a script that parses a json file from the root of `kubejs` folder, that way we don't need to track two scripts for changes, and can just update the json file 😄

A bit of a crude idea, but it might work.

**Comment by MuteTiefling** [comment]
Not a bad idea, honestly

**Comment by NielsPilgaard** [comment]
I'd prefer to keep the tooltip for disabled items, it does prevent a little confusion here and there :P

**Comment by MuteTiefling** [comment]
Fair enough. Shall I proceed with Kanz suggestion then? Or just keep it as is with notes to change both locations?

**Comment by NielsPilgaard** [comment]
I think double code is the simplest, while Kanz's suggestion is easiest for us to maintain. Please proceed with the option you prefer :D

**Comment by MuteTiefling** [comment]
Alright, I think that does it. Hopefully those two issues get cleared up relatively soon.

**Comment by NielsPilgaard** [comment]
> Alright, I think that does it. Hopefully those two issues get cleared up relatively soon.

Do we need to wait with merging this until they're resolved?

**Comment by MuteTiefling** [comment]
The duplicate info panes should already be fixed in the next kubejs release, so that's fine. 

I'm not sure the other one is even a kubejs issue now, however, since I'm getting apothic spawner errors in the logs when that happens. Might be better to wait though. As is, if we do release with this, players will have an odd experience loading their world

**Comment by MuteTiefling** [comment]
Yeah, removing Apothic Spawners also resolves the world load issue. I'll report to Shadows as well and see what they think. 

We're probably OK to merge this though. I think we're waiting for a fair few mods to update before we're even stable again, right? Your call.

**Comment by NielsPilgaard** [comment]
> We're probably OK to merge this though. I think we're waiting for a fair few mods to update before we're even stable again, right? Your call.

We are yeah, might as well merge :D

**Pull request merged**
