### PR TITLE
General Improvements

### PR DESCRIPTION
**Pull request by MuteTiefling**
EnderIO can now make Steel
The recipe will be somewhat similar to Dark Steel
image

This means if the player forgets to add obsidian, they'll get steel instead of darksteel. Therefore a helper recipe will convert steel to dark steel if this happens.
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
#173

**Comment by MuteTiefling** [comment]
Cobblegen Galore recipes re-worked as they were far too cheap, making the lower tiers useless. Observers now accept Certus as well as Nether Quartz to make them more accessible. 

cobblegengalore_shaped_block_gen_stone
cobblegengalore_shaped_block_gen_copper
cobblegengalore_shaped_block_gen_iron
cobblegengalore_shaped_block_gen_gold
cobblegengalore_shaped_block_gen_emerald
cobblegengalore_shaped_block_gen_diamond
cobblegengalore_shaped_block_gen_netherite

**Comment by MuteTiefling** [comment]
Adds silver and dark gem ore to AA miner

**Review by NielsPilgaard — APPROVED** [review]
LGTM, solid work😊

**Pull request merged**
